# Generated by Django 4.2.7 on 2025-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.IntegerField()),
                ('title', models.CharField(default='未命名文档', max_length=200)),
                ('document_type', models.CharField(max_length=50)),
                ('current_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_id', models.IntegerField()),
                ('version_number', models.IntegerField()),
                ('content', models.TextField()),
                ('raw_content', models.TextField()),
                ('formatted_content', models.TextField()),
                ('version_note', models.CharField(blank=True, max_length=500)),
                ('operation_type', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('document_id', 'version_number')},
            },
        ),
    ]
